# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: test
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
      mode: always

# Logger Config
logging:
  level:
#    com.llmcu.imooc.mybatisplus.basic.environment: debug
    com.llmcu.imooc.mybatisplus.basic: debug

# 修改默认全局id-type后，跟随全局的就会出问题
#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto
