DROP TABLE IF EXISTS sys_user;

CREATE TABLE sys_user
(
	id BIGINT NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	age INT NULL DEFAULT NULL COMMENT '年龄',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS sys_user01;

-- CREATE TABLE sys_user01
-- (
-- 	id BIGINT NOT NULL COMMENT '主键ID',
-- 	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
-- 	age INT NULL DEFAULT NULL COMMENT '年龄',
-- 	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
-- 	PRIMARY KEY (id)
-- );
CREATE TABLE sys_user01
(
	id BIGINT auto_increment COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	age INT NULL DEFAULT NULL COMMENT '年龄',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	PRIMARY KEY (id)
);


DROP TABLE IF EXISTS sys_user02;

CREATE TABLE sys_user02
(
	id BIGINT NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	age INT NULL DEFAULT NULL COMMENT '年龄',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS sys_user03;

CREATE TABLE sys_user03
(
	id BIGINT NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	age INT NULL DEFAULT NULL COMMENT '年龄',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	PRIMARY KEY (id)
);

DROP SEQUENCE IF EXISTS SEQ_SYS_USER;

CREATE SEQUENCE SEQ_SYS_USER
    START WITH 1
    INCREMENT BY 1;

DROP TABLE IF EXISTS sys_user04;

CREATE TABLE sys_user04
(
	id BIGINT NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	age INT NULL DEFAULT NULL COMMENT '年龄',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS sys_user05;

CREATE TABLE sys_user05
(
	id VARCHAR(50) NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	age INT NULL DEFAULT NULL COMMENT '年龄',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	PRIMARY KEY (id)
);

